Disable serverless-sentry plugin
Running into issues when running tests on travis:

https://travis-ci.org/cityofaustin/ctxfloods-backend/builds/370806468

https://travis-ci.org/cityofaustin/ctxfloods-backend/builds/370806468#L834

```
TypeError: Cannot read property 'done' of null
    at Object.handle (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/serverless-sentry-lib/index.js:313:57)
    at app.all (/home/travis/build/cityofaustin/ctxfloods-backend/localServer.js:24:18)
    at Layer.handle [as handle_request] (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:137:13)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:317:13)
    at /home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/express/lib/router/index.js:275:10)
    at /home/travis/build/cityofaustin/ctxfloods-backend/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/raw-body/index.js:224:16)
    at done (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/travis/build/cityofaustin/ctxfloods-backend/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:5426) UnhandledPromiseRejectionWarning: Error: Invalid status code: 500
(node:5426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```